# Generated by Django 3.2 on 2023-11-02 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0002_comentario_idpublicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='delete_comentario',
            field=models.BooleanField(default=False),
        ),
    ]
