# Generated by Django 3.2 on 2023-11-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0003_comentario_delete_comentario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='delete_comentario',
        ),
    ]
