# Generated by Django 3.2 on 2023-10-18 22:17

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id_seccion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_seccion', models.CharField(choices=[('Articulo', 'Articulo'), ('Noticia', 'Noticia'), ('Galeria', 'Galeria')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('idPublicacion', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=100)),
                ('bajada', models.TextField(null=True)),
                ('cuerpo', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.FileField(blank=True, null=True, upload_to='documentos/')),
                ('imagen_portada', models.ImageField(blank=True, null=True, upload_to='imagen_portada/')),
                ('equipamiento', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('detalle', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('imagen_marcador', models.ImageField(blank=True, null=True, upload_to='imagen_marcador/')),
                ('estado', models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado'), ('Archivado', 'Archivado')], default='Borrador', max_length=10)),
                ('editor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editor_post', to=settings.AUTH_USER_MODEL)),
                ('seccion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publicaciones.seccion')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publicaciones_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
